<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="CreateProfiles" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\..\root_configuration.props"/>
  <Import Project="..\..\root_assembly_configuration.props"/>

    <UsingTask TaskName="ProjectCheckerTask" AssemblyFile="ProjectCheckerTask.dll" />
    <Target Name="CheckProjects">
        <Message Text="UserSRCDir $(UserSRCDir)" Importance="High" />
        <Message Text="UserBINDir $(UserBINDir)" Importance="High" />
        <ProjectCheckerTask SolutionsPath="$(SolutionsPath)"
                            BreakBuild="false"
                            CreateSonarProfile="false"
                            OutXmlPath="$(UserSRCDir)"
                        />
    </Target>

    <UsingTask TaskName="ProjectCheckerTask" AssemblyFile="ProjectCheckerTask.dll" />
    <Target Name="CreateProfiles">
        <Message Text="UserSRCDir $(UserSRCDir)" Importance="High" />
        <Message Text="UserBINDir $(UserBINDir)" Importance="High" />
        <ProjectCheckerTask CreateSonarProfile="true"/>
    </Target>


    <UsingTask TaskName="ProjectCheckerTask" AssemblyFile="ProjectCheckerTask.dll" />
    <Target Name="PreprocessAssemblies">
        <Message Text="UserSRCDir $(UserSRCDir)" Importance="High" />
        <Message Text="UserBINDir $(UserBINDir)" Importance="High" />
        <ProjectCheckerTask  SolutionsPath="$(UserSRCDir)/CLI/IFCExport.NET/ExternalDependencies/developer-kit-17.0/UserApp/UserApp.sln;
                                            $(UserSRCDir)/CLI/IFCExport.NET/IFCExport.NET.sln;
                                            $(UserSRCDir)/CLI/IFCExport.NET/IFCExportPlugin/IFCExportPlugin.sln;
                                            $(UserSRCDir)/CLI/ObjectConverter/ObjectConverterPlugin.sln;
                                            $(UserSRCDir)/CLI/SkpImport/SkpImport.sln;
                                            $(UserSRCDir)/Core/Analysis/Analysis.sln;
                                            $(UserSRCDir)/Core/BrepStorage/BrepStorage.sln;
                                            $(UserSRCDir)/Core/Catalogs/Catalogs.sln;
                                            $(UserSRCDir)/Core/Common/Common.sln;
                                            $(UserSRCDir)/Core/Contracts/Contracts.sln;
                                            $(UserSRCDir)/Core/Dimensioning/Dimensioning.sln;
                                            $(UserSRCDir)/Core/Drawings/Drawings.sln;
                                            $(UserSRCDir)/Core/Environment/Environment.sln;
                                            $(UserSRCDir)/Core/ImporterComponent/ImporterComponent.sln;
                                            $(UserSRCDir)/Core/Model/Model.sln;
                                            $(UserSRCDir)/Core/Reinforcement/Reinforcement.sln;
                                            $(UserSRCDir)/Core/Solids/Solids.sln;
                                            $(UserSRCDir)/Core/TeklaStructures/TeklaStructures.sln;
                                            $(UserSRCDir)/DeveloperDoc/build/DeveloperDoc.sln;
                                            $(UserSRCDir)/DeveloperKit/DeveloperKit.sln;
                                            $(UserSRCDir)/DirectManipulation/Tekla.DirectManipulation.sln;
                                            $(UserSRCDir)/DotNetInterface/DotNetInterface.sln;
                                            $(UserSRCDir)/DotNetInterface/ExcelPluginNew/ExcelPlugin.sln;
                                            $(UserSRCDir)/DotNetInterface/Tekla.Structures.DrawingsDatatypes.sln;
                                            $(UserSRCDir)/DotNetInterface/Tekla.Structures.ModelDatatypes.sln;
                                            $(UserSRCDir)/DotNetInterface/Test/Tekla.Structures.Drawing.Test/Tekla.Structures.Drawing.Test.sln;
                                            $(UserSRCDir)/DotNetInterface/Test/Tekla.Structures.Model.Test/Tekla.Structures.Model.Test.sln;
                                            $(UserSRCDir)/Test/DrawingTester/DrawingTester.sln;
                                            $(UserSRCDir)/Test/ModelTester/Modeltester.sln;
                                            $(UserSRCDir)/Test/ModelTester/Prototypes/Prototypes.sln;
                                            $(UserSRCDir)/Test/StackCollector/StackCollector.sln;
                                            $(UserSRCDir)/TSProjects/A-insinöörit/Model/Plugins/SoclePanel/SoclePanel.sln;
                                            $(UserSRCDir)/TSProjects/AceCAD/Projects/ConvertPDFtoReferenceObject/PDFReferenceModel/PDFReferenceModel.sln;
                                            $(UserSRCDir)/TSProjects/AceCAD/Projects/ConvertPDFtoReferenceObject/Proto1 PDFtoDXF/PDFtoDXF.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/CS.Library/CS.Library.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Drawings/Applications/DrawingDimensioningTools_RuleCreator/DrawingDimensionTool_RuleCreator.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Drawings/Plugins/DimensioningTool/DimensioningTool.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Model/Applications/BvbsExportExample/BvbsExport.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Model/Plugins/FloorToolPlugin/FloorToolPlugin.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Model/Plugins/HollowCoreOpeningTool/HollowCoreOpeningTool.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Model/Plugins/RingReinforcement/RingReinforcement.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Tools/Elematic Eliplan(68,69) Installer/Elematic_eliplan(68,69)_Installer.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Tools/INPEditor/INPEditor.sln;
                                            $(UserSRCDir)/TSProjects/Dimensioning/DimensioningPlugins.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/DirectManipulation.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/DirectManipulationPlugins/DirectManipulation.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/DirectManipulationPlugins/DM_FeatureMesh/DmFeatureMesh.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/DirectManipulationPlugins/DM_FeatureRebar/DmFeatureRebar.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/DM_FeatureRebar/DmFeatureRebar.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/dm_tutorial/dm_tutorial.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/ModelPlugins/ModelPlugins.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Tekla.Structures.Features.Proto.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Tekla.Structures.Features.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Drawings/DrawingApps.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Applications/BetsyAttributeSetter/BetsyAttributeSetter.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Applications/BvbsExport/BvbsExport.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Applications/HollowCoreChecker/HollowCoreChecker.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Applications/RebarRecognition/RebarBendingRecognition.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Plugins/Elementation/Elementation.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Plugins/FloorLayoutTool/FloorLayoutTool.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Plugins/RebarShapeByCatalog/RebarShapeByCatalog.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Plugins/WallToWallConnection/WallToWallConnection.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Proto/Plugins/ReinforcementSet/ReinforcementSet.sln;
                                            $(UserSRCDir)/TSProjects/Examples/Model/Applications/CurvedBeam/Curved Beam.sln;
                                            $(UserSRCDir)/TSProjects/Examples/Model/Applications/DirectoryBrowsingTool/DirectoryBrowsingTool.sln;
                                            $(UserSRCDir)/TSProjects/EXT_DOT_APPS/DrawingApps.sln;
                                            $(UserSRCDir)/TSProjects/EXT_DOT_APPS/DrawingAppsInstallers.sln;
                                            $(UserSRCDir)/TSProjects/EXT_DOT_APPS/ModelApps.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Drawings/Applications/TopInFormMarker/TopInFormMarker.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Applications/ACNSequencer/ACNSequencer.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Applications/AssignSequentialUDA/AssignSequentialUDA.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/DoubleTeeComponents/DTComponents.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/DoubleTeeRidgeBeam/DoubleTeeRidgeBeam.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/HollowCoreSlabPlugins/HollowCoreSlabPlugins.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/HollowCoreSlabToEdgeBeam/HollowCoreSlabToEdgeBeam.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/WallPanelCornerConnection/WallPanelCornerConnection.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/WallPanelShoeConnection/WallPanelShoeConnection.sln;
                                            $(UserSRCDir)/TSProjects/Santon/CS.Library/CS.Library.sln;
                                            $(UserSRCDir)/TSProjects/Santon/Drawings/Applications/DimensionCreator/DimensionCreator.sln;
                                            $(UserSRCDir)/TSProjects/Santon/Drawings/Plugins/DimensioningTool/DimensioningTool.sln;
                                            $(UserSRCDir)/TSProjects/Santon/PDMS/Work/TS_PDMS/TS_PDMS.sln;
                                            $(UserSRCDir)/TSProjects/Santon/PDMS/Work/TS_PDMS.sln;
                                            $(UserSRCDir)/TSProjects/Tekla.Structures.Features.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Custom Properties/CustomProperties.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Drawings/DrawingApps.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Model/Applications/ModelCheckerSuite/ModelCheckerSuite.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Model/Applications/ModelCheckUpsideDown/ModelCheckerPlugins_UpsideDown/ModelCheckerSuite.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Model/Applications/ModelCheckUpsideDown/src/Backup/ModelCheckerSuite.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Model/Applications/ModelCheckUpsideDown/src/ModelCheckerSuite.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Model/ModelApps.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Proto/DevTools/DevTools.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Proto/DrawingPreviewPrototype/DXF_Viewer/DXF_Viewer.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Proto/xitTools/xitTools.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Proto/XMLtoAILconverter/XMLtoAILconverter.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Tools/Tools.sln; 
                                            $(UserSRCDir)/Dot_Apps/Analysis/AnalysisApps.sln;
                                            $(UserSRCDir)/Dot_Apps/Analysis/Applications/AnalysisResultsToExcel/AnalysisResultsToExcel.sln;
                                            $(UserSRCDir)/Dot_Apps/Analysis/Applications/Design/DesignManagerSetup/DesignManagerSetup.sln;
                                            $(UserSRCDir)/Dot_Apps/ApplicationFeatures/ApplicationFeatures.sln;
                                            $(UserSRCDir)/Dot_Apps/Catalog/Catalogs.sln;
                                            $(UserSRCDir)/Dot_Apps/Catalog/ComponentCatalog/ComponentCatalog.sln;
                                            $(UserSRCDir)/Dot_Apps/Catalog/ComponentCatalog/Proto/CatalogInterfaces/CatalogInterfaces.sln;
                                            $(UserSRCDir)/Dot_Apps/Catalog/ComponentCatalog/Proto/CatalogObjects/CatalogObjects.sln;
                                            $(UserSRCDir)/Dot_Apps/Catalog/ComponentCatalog/Proto/StuffCatalog/StuffCatalog.sln;
                                            $(UserSRCDir)/Dot_Apps/ConstructionManagement/ConstructionManagement.sln;
                                            $(UserSRCDir)/Dot_Apps/ContentPortal/PortalFeature/Tekla.BIM.ContentPortal.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Applications/PredefinedViewCreator/PredefinedViewCreator.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Applications/SDIExport/SDIExport32b/SDIExport.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Applications/SDIExport/SDIExport64b/SDIExport64b.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/DimensioningApps.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/DrawingApps.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/DrawingAppsGER.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/DrawingAppsInstallers.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Plugins/Dimensioning/BasicDimensioningPlugins/BasicDimensioningPlugins.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Plugins/Dimensioning/WeldDimensioningPlugin/WeldDimensioningPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Plugins/ProfileList/ProfileList.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Tools/DataBaseObjectExtension/DataBaseObjectExtension.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Tools/DrawingAttributesConverter/DrawingAttributesConverter.sln;
                                            $(UserSRCDir)/Dot_Apps/Examples/CodeExamples/CodeExamples.sln;
                                            $(UserSRCDir)/Dot_Apps/Examples/Examples.sln;
                                            $(UserSRCDir)/Dot_Apps/Library/AppsClassLibrary.sln;
                                            $(UserSRCDir)/Dot_Apps/Library/HyperTooltips/HyperTooltips.sln;
                                            $(UserSRCDir)/Dot_Apps/Library/Logging/Logging.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/CopyGADrawing/GADrawingCopier.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/DirectoryBrowsingTool/DirectoryBrowsingTool.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/EdgeChamferRemover/EdgeChamferRemover.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/IFCPropertySetConfigurationTool/IFCPropertySetConfigurationTool.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/ImportFromTeklaBIMsight/ImportFromTeklaBIMsight.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/OffsetTool/OffsetTool.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/PhaseCreator/PhaseCreator.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/PublishToTeklaBIMSight/PublishToTeklaBIMSight.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/RebarBendingRecognition/RebarShapeInterface/RebarShapeInterface.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/Redlining/Solution/Redlining.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/TubeNC.Export/Tube.NC.Export.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/ModelApps.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/ModelAppsGER.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/ModelAppsInstallers.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/ModelApps_32_64.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Plugins/ChairReinforcement/ChairReinforcement.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Plugins/IFCGridExport/IfcGridExport.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Plugins/WallOpening/WallOpening.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Test/ObjectConverterPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Tools/CatalogExtension/CatalogExtension.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Tools/ComponentExtension/ComponentExtension.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Tools/ImporterComponent/ImporterComponent.sln;
                                            $(UserSRCDir)/Dot_Apps/ModelWin32X64/ModelApps_32_64.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/AssociativityPlugin/AssociativityPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/Common/Common.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/ComplexLinePlugin/ComplexLinePlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/ConcreteLibrary/ConcreteLibrary.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/ConcreteLibrary/ExtensionTools/ExtensionTools.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/DrawingAssociativity/DrawingAssociativity.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/DrawingPresentationPlugins/GridLabelTextExchanger/GridLabelTextExchanger.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/Drawings/Plugins/Dimensioning/DummyDimensioningPlugin/DummyDimensioningPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/Drawings/Plugins/Dimensioning/SectionTestDimensioningPlugin/SectionTestDimensioningPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/Drawings/Plugins/Presentation/WeldGeometryPresentation/WeldGeometryPresentation.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/ObjectConverter/ObjectConverter.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/PluginIntelligenceTester/PluginIntelligenceTester.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/PointPlotterPlugin/PointPlotterPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/ProtoApps.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/RebarSplice/SpliceRebar.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/SDIExportTestBench/SDIExportTestBench.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/SeparateOnePartFromIFC/SeparateOnePartFromIFC.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/TeklaUpdater/TeklaUpdater.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/TeklaUpdater/TeklaUpdater2008.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/TemplateGraphicalField/TemplateGraphicalField.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/WebConnector/WebConnector.sln;
                                            $(UserSRCDir)/Dot_Apps/ReferenceModelPlugin/ReferenceModelPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Sharing/Sharing.sln;
                                            $(UserSRCDir)/Dot_Apps/Tools/SupportTool/SupportTool.sln;
                                            $(UserSRCDir)/Dot_Apps/Tools/SupportToolV2/SupportTool_V2.sln;
                                            $(UserSRCDir)/Dot_Apps/Tools/TeklaDotnetTools.sln;
                                            $(UserSRCDir)/Dot_Apps/Warehouse/Tekla.Warehouse.sln"                                            
                            BreakBuild="false"
                            CreateSonarProfile="true"
                            OutXmlPath="$(UserSRCDir)\"
                            PreprocessProjectFiles="true"
                        />
    </Target>
    
    <UsingTask TaskName="ProjectCheckerTask" AssemblyFile="ProjectCheckerTask.dll" />
    <Target Name="CheckStructures">
        <Message Text="UserSRCDir $(UserSRCDir)" Importance="High" />
        <Message Text="UserBINDir $(UserBINDir)" Importance="High" />
        <ProjectCheckerTask  SolutionsPath="$(UserSRCDir)/CLI/IFCExport.NET/ExternalDependencies/developer-kit-17.0/UserApp/UserApp.sln;
                                            $(UserSRCDir)/CLI/IFCExport.NET/IFCExport.NET.sln;
                                            $(UserSRCDir)/CLI/IFCExport.NET/IFCExportPlugin/IFCExportPlugin.sln;
                                            $(UserSRCDir)/CLI/ObjectConverter/ObjectConverterPlugin.sln;
                                            $(UserSRCDir)/CLI/SkpImport/SkpImport.sln;
                                            $(UserSRCDir)/Core/Analysis/Analysis.sln;
                                            $(UserSRCDir)/Core/BrepStorage/BrepStorage.sln;
                                            $(UserSRCDir)/Core/Catalogs/Catalogs.sln;
                                            $(UserSRCDir)/Core/Common/Common.sln;
                                            $(UserSRCDir)/Core/Contracts/Contracts.sln;
                                            $(UserSRCDir)/Core/Dimensioning/Dimensioning.sln;
                                            $(UserSRCDir)/Core/Drawings/Drawings.sln;
                                            $(UserSRCDir)/Core/Environment/Environment.sln;
                                            $(UserSRCDir)/Core/ImporterComponent/ImporterComponent.sln;
                                            $(UserSRCDir)/Core/Model/Model.sln;
                                            $(UserSRCDir)/Core/Reinforcement/Reinforcement.sln;
                                            $(UserSRCDir)/Core/Solids/Solids.sln;
                                            $(UserSRCDir)/Core/TeklaStructures/TeklaStructures.sln;
                                            $(UserSRCDir)/DeveloperDoc/build/DeveloperDoc.sln;
                                            $(UserSRCDir)/DeveloperKit/DeveloperKit.sln;
                                            $(UserSRCDir)/DirectManipulation/Tekla.DirectManipulation.sln;
                                            $(UserSRCDir)/DotNetInterface/DotNetInterface.sln;
                                            $(UserSRCDir)/DotNetInterface/ExcelPluginNew/ExcelPlugin.sln;
                                            $(UserSRCDir)/DotNetInterface/Tekla.Structures.DrawingsDatatypes.sln;
                                            $(UserSRCDir)/DotNetInterface/Tekla.Structures.ModelDatatypes.sln;
                                            $(UserSRCDir)/DotNetInterface/Test/Tekla.Structures.Drawing.Test/Tekla.Structures.Drawing.Test.sln;
                                            $(UserSRCDir)/DotNetInterface/Test/Tekla.Structures.Model.Test/Tekla.Structures.Model.Test.sln;
                                            $(UserSRCDir)/Test/DrawingTester/DrawingTester.sln;
                                            $(UserSRCDir)/Test/ModelTester/Modeltester.sln;
                                            $(UserSRCDir)/Test/ModelTester/Prototypes/Prototypes.sln;
                                            $(UserSRCDir)/Test/StackCollector/StackCollector.sln"
                            BreakBuild="false"
                            CreateSonarProfile="true"
                            OutXmlPath="$(UserSRCDir)\"
                        />
    </Target>

    
    <UsingTask TaskName="ProjectCheckerTask" AssemblyFile="ProjectCheckerTask.dll" />
    <Target Name="CheckTSProjects">
        <Message Text="UserSRCDir $(UserSRCDir)" Importance="High" />
        <Message Text="UserBINDir $(UserBINDir)" Importance="High" />
        <ProjectCheckerTask  SolutionsPath="$(UserSRCDir)/TSProjects/A-insinöörit/Model/Plugins/SoclePanel/SoclePanel.sln;
                                            $(UserSRCDir)/TSProjects/AceCAD/Projects/ConvertPDFtoReferenceObject/PDFReferenceModel/PDFReferenceModel.sln;
                                            $(UserSRCDir)/TSProjects/AceCAD/Projects/ConvertPDFtoReferenceObject/Proto1 PDFtoDXF/PDFtoDXF.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/CS.Library/CS.Library.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Drawings/Applications/DrawingDimensioningTools_RuleCreator/DrawingDimensionTool_RuleCreator.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Drawings/Plugins/DimensioningTool/DimensioningTool.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Model/Applications/BvbsExportExample/BvbsExport.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Model/Plugins/FloorToolPlugin/FloorToolPlugin.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Model/Plugins/HollowCoreOpeningTool/HollowCoreOpeningTool.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Model/Plugins/RingReinforcement/RingReinforcement.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Tools/Elematic Eliplan(68,69) Installer/Elematic_eliplan(68,69)_Installer.sln;
                                            $(UserSRCDir)/TSProjects/Construsoft/Tools/INPEditor/INPEditor.sln;
                                            $(UserSRCDir)/TSProjects/Dimensioning/DimensioningPlugins.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/DirectManipulation.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/DirectManipulationPlugins/DirectManipulation.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/DirectManipulationPlugins/DM_FeatureMesh/DmFeatureMesh.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/DirectManipulationPlugins/DM_FeatureRebar/DmFeatureRebar.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/DM_FeatureRebar/DmFeatureRebar.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/dm_tutorial/dm_tutorial.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Proto/ModelPlugins/ModelPlugins.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Tekla.Structures.Features.Proto.sln;
                                            $(UserSRCDir)/TSProjects/DirectManipulation/Tekla.Structures.Features.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Drawings/DrawingApps.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Applications/BetsyAttributeSetter/BetsyAttributeSetter.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Applications/BvbsExport/BvbsExport.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Applications/HollowCoreChecker/HollowCoreChecker.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Applications/RebarRecognition/RebarBendingRecognition.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Plugins/Elementation/Elementation.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Plugins/FloorLayoutTool/FloorLayoutTool.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Plugins/RebarShapeByCatalog/RebarShapeByCatalog.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Model/Plugins/WallToWallConnection/WallToWallConnection.sln;
                                            $(UserSRCDir)/TSProjects/Eurocode/Proto/Plugins/ReinforcementSet/ReinforcementSet.sln;
                                            $(UserSRCDir)/TSProjects/Examples/Model/Applications/CurvedBeam/Curved Beam.sln;
                                            $(UserSRCDir)/TSProjects/Examples/Model/Applications/DirectoryBrowsingTool/DirectoryBrowsingTool.sln;
                                            $(UserSRCDir)/TSProjects/EXT_DOT_APPS/DrawingApps.sln;
                                            $(UserSRCDir)/TSProjects/EXT_DOT_APPS/DrawingAppsInstallers.sln;
                                            $(UserSRCDir)/TSProjects/EXT_DOT_APPS/ModelApps.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Drawings/Applications/TopInFormMarker/TopInFormMarker.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Applications/ACNSequencer/ACNSequencer.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Applications/AssignSequentialUDA/AssignSequentialUDA.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/DoubleTeeComponents/DTComponents.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/DoubleTeeRidgeBeam/DoubleTeeRidgeBeam.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/HollowCoreSlabPlugins/HollowCoreSlabPlugins.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/HollowCoreSlabToEdgeBeam/HollowCoreSlabToEdgeBeam.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/WallPanelCornerConnection/WallPanelCornerConnection.sln;
                                            $(UserSRCDir)/TSProjects/Ramboll/Model/Plugins/WallPanelShoeConnection/WallPanelShoeConnection.sln;
                                            $(UserSRCDir)/TSProjects/Santon/CS.Library/CS.Library.sln;
                                            $(UserSRCDir)/TSProjects/Santon/Drawings/Applications/DimensionCreator/DimensionCreator.sln;
                                            $(UserSRCDir)/TSProjects/Santon/Drawings/Plugins/DimensioningTool/DimensioningTool.sln;
                                            $(UserSRCDir)/TSProjects/Santon/PDMS/Work/TS_PDMS/TS_PDMS.sln;
                                            $(UserSRCDir)/TSProjects/Santon/PDMS/Work/TS_PDMS.sln;
                                            $(UserSRCDir)/TSProjects/Tekla.Structures.Features.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Custom Properties/CustomProperties.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Drawings/DrawingApps.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Model/Applications/ModelCheckerSuite/ModelCheckerSuite.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Model/Applications/ModelCheckUpsideDown/ModelCheckerPlugins_UpsideDown/ModelCheckerSuite.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Model/Applications/ModelCheckUpsideDown/src/Backup/ModelCheckerSuite.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Model/Applications/ModelCheckUpsideDown/src/ModelCheckerSuite.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Model/ModelApps.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Proto/DevTools/DevTools.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Proto/DrawingPreviewPrototype/DXF_Viewer/DXF_Viewer.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Proto/xitTools/xitTools.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Proto/XMLtoAILconverter/XMLtoAILconverter.sln;
                                            $(UserSRCDir)/TSProjects/XITing/Tools/Tools.sln"
                            BreakBuild="false"
                            CreateSonarProfile="true"
                            OutXmlPath="$(UserSRCDir)\TSProjects"
                        />
    </Target>

    <UsingTask TaskName="ProjectCheckerTask" AssemblyFile="ProjectCheckerTask.dll" />
    <Target Name="CheckDotApps">
        <Message Text="UserSRCDir $(UserSRCDir)" Importance="High" />
        <Message Text="UserBINDir $(UserBINDir)" Importance="High" />
        <ProjectCheckerTask  SolutionsPath="$(UserSRCDir)/Dot_Apps/Analysis/AnalysisApps.sln;
                                            $(UserSRCDir)/Dot_Apps/Analysis/Applications/AnalysisResultsToExcel/AnalysisResultsToExcel.sln;
                                            $(UserSRCDir)/Dot_Apps/Analysis/Applications/Design/DesignManagerSetup/DesignManagerSetup.sln;
                                            $(UserSRCDir)/Dot_Apps/ApplicationFeatures/ApplicationFeatures.sln;
                                            $(UserSRCDir)/Dot_Apps/Catalog/Catalogs.sln;
                                            $(UserSRCDir)/Dot_Apps/Catalog/ComponentCatalog/ComponentCatalog.sln;
                                            $(UserSRCDir)/Dot_Apps/Catalog/ComponentCatalog/Proto/CatalogInterfaces/CatalogInterfaces.sln;
                                            $(UserSRCDir)/Dot_Apps/Catalog/ComponentCatalog/Proto/CatalogObjects/CatalogObjects.sln;
                                            $(UserSRCDir)/Dot_Apps/Catalog/ComponentCatalog/Proto/StuffCatalog/StuffCatalog.sln;
                                            $(UserSRCDir)/Dot_Apps/ConstructionManagement/ConstructionManagement.sln;
                                            $(UserSRCDir)/Dot_Apps/ContentPortal/PortalFeature/Tekla.BIM.ContentPortal.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Applications/PredefinedViewCreator/PredefinedViewCreator.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Applications/SDIExport/SDIExport32b/SDIExport.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Applications/SDIExport/SDIExport64b/SDIExport64b.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/DimensioningApps.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/DrawingApps.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/DrawingAppsGER.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/DrawingAppsInstallers.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Plugins/Dimensioning/BasicDimensioningPlugins/BasicDimensioningPlugins.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Plugins/Dimensioning/WeldDimensioningPlugin/WeldDimensioningPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Plugins/ProfileList/ProfileList.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Tools/DataBaseObjectExtension/DataBaseObjectExtension.sln;
                                            $(UserSRCDir)/Dot_Apps/Drawings/Tools/DrawingAttributesConverter/DrawingAttributesConverter.sln;
                                            $(UserSRCDir)/Dot_Apps/Examples/CodeExamples/CodeExamples.sln;
                                            $(UserSRCDir)/Dot_Apps/Examples/Examples.sln;
                                            $(UserSRCDir)/Dot_Apps/Library/AppsClassLibrary.sln;
                                            $(UserSRCDir)/Dot_Apps/Library/HyperTooltips/HyperTooltips.sln;
                                            $(UserSRCDir)/Dot_Apps/Library/Logging/Logging.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/CopyGADrawing/GADrawingCopier.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/DirectoryBrowsingTool/DirectoryBrowsingTool.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/EdgeChamferRemover/EdgeChamferRemover.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/IFCPropertySetConfigurationTool/IFCPropertySetConfigurationTool.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/ImportFromTeklaBIMsight/ImportFromTeklaBIMsight.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/OffsetTool/OffsetTool.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/PhaseCreator/PhaseCreator.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/PublishToTeklaBIMSight/PublishToTeklaBIMSight.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/RebarBendingRecognition/RebarShapeInterface/RebarShapeInterface.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/Redlining/Solution/Redlining.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Applications/TubeNC.Export/Tube.NC.Export.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/ModelApps.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/ModelAppsGER.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/ModelAppsInstallers.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/ModelApps_32_64.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Plugins/ChairReinforcement/ChairReinforcement.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Plugins/IFCGridExport/IfcGridExport.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Plugins/WallOpening/WallOpening.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Test/ObjectConverterPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Tools/CatalogExtension/CatalogExtension.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Tools/ComponentExtension/ComponentExtension.sln;
                                            $(UserSRCDir)/Dot_Apps/Model/Tools/ImporterComponent/ImporterComponent.sln;
                                            $(UserSRCDir)/Dot_Apps/ModelWin32X64/ModelApps_32_64.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/AssociativityPlugin/AssociativityPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/Common/Common.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/ComplexLinePlugin/ComplexLinePlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/ConcreteLibrary/ConcreteLibrary.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/ConcreteLibrary/ExtensionTools/ExtensionTools.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/DrawingAssociativity/DrawingAssociativity.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/DrawingPresentationPlugins/GridLabelTextExchanger/GridLabelTextExchanger.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/Drawings/Plugins/Dimensioning/DummyDimensioningPlugin/DummyDimensioningPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/Drawings/Plugins/Dimensioning/SectionTestDimensioningPlugin/SectionTestDimensioningPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/Drawings/Plugins/Presentation/WeldGeometryPresentation/WeldGeometryPresentation.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/ObjectConverter/ObjectConverter.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/PluginIntelligenceTester/PluginIntelligenceTester.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/PointPlotterPlugin/PointPlotterPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/ProtoApps.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/RebarSplice/SpliceRebar.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/SDIExportTestBench/SDIExportTestBench.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/SeparateOnePartFromIFC/SeparateOnePartFromIFC.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/TeklaUpdater/TeklaUpdater.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/TeklaUpdater/TeklaUpdater2008.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/TemplateGraphicalField/TemplateGraphicalField.sln;
                                            $(UserSRCDir)/Dot_Apps/Proto/WebConnector/WebConnector.sln;
                                            $(UserSRCDir)/Dot_Apps/ReferenceModelPlugin/ReferenceModelPlugin.sln;
                                            $(UserSRCDir)/Dot_Apps/Sharing/Sharing.sln;
                                            $(UserSRCDir)/Dot_Apps/Tools/SupportTool/SupportTool.sln;
                                            $(UserSRCDir)/Dot_Apps/Tools/SupportToolV2/SupportTool_V2.sln;
                                            $(UserSRCDir)/Dot_Apps/Tools/TeklaDotnetTools.sln;
                                            $(UserSRCDir)/Dot_Apps/Warehouse/Tekla.Warehouse.sln"
                            BreakBuild="false"
                            CreateSonarProfile="true"
                            OutXmlPath="$(UserSRCDir)\Dot_Apps"
                        />
    </Target>
    
</Project>
